# Generated by Django 3.1.7 on 2021-12-15 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20211215_1321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctionitem',
            name='bid_amt',
        ),
    ]
